version: "3"

services:
  mysql:
    image: mysql:8.0
    restart: always
    networks:
      - aptiw_network
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "$DB_PORT:$DB_PORT"

  adminer:
    image: adminer:4.8.1
    depends_on:
      - mysql
    networks:
      - aptiw_network
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: galkaev

    env_file:
      - .env

networks:
  aptiw_network:
    driver: bridge
